# Generated by Django 5.2.6 on 2025-09-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('futwear', 'Futwear'), ('cloathing item', 'Cloathing item'), ('merchant dice', 'Merchant dice'), ('others', 'Others')], default='update', max_length=20),
        ),
    ]
