# Generated by Django 5.2.6 on 2025-09-21 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_employee_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('futwear', 'Futwear'), ('cloathing item', 'Cloathing item'), ('merchant dice', 'Merchant dice'), ('spourts item', 'Spourts item'), ('others', 'Others')], default='update', max_length=20),
        ),
    ]
