# Generated by Django 5.2.6 on 2025-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_user_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('futwear', 'Futwear'), ('cloathing item', 'Cloathing item'), ('merchant dice', 'Merchant dice'), ('spourts item', 'Spourts item'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
