# Generated by Django 5.2.6 on 2025-09-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('futwear', 'Futwear'), ('cloathing itm', 'Cloathing itm'), ('merchant dice', 'Merchant dice'), ('spourts itm', 'Spourts itm'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
